
services:
  pgsql:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Vad310865!
      POSTGRES_DATABASE: mvc_hibernate
    volumes:
      - pgsql_data:/var/lib/postgresql
    restart: on-failure
    container_name: pgsql
    networks:
      - retail-task-dev

volumes:
  pgsql_data:

networks:
  retail-task-dev:
