name: SBGitActBDMySQL

on:
  push:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      # Запускаем MySQL как сервис, который будет доступен для тестов
      mysql:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: Vad310865!
          POSTGRES_DB: mvc_hibernate
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d mvc_hibernate"
          --health-interval "10s"
          --health-timeout "5s"
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          cache: 'maven'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install
        #run: mvn -B clean install

      - name: Test with MySQL # Запускаем тесты, которые подключаются к сервису MySQL
        run: mvn test
        env:
          # Передаем параметры подключения к базе данных в переменные окружения
          SPRING_DATASOURCE_URL: jdbc:postgresql://127.0.0.1:5432/mvc_hibernate
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: Vad310865!


#      - name: Set up MySQL
#        run: |
#          # Команды для установки и запуска MySQL на локальной машине (не в Docker)
#          # Для продакшена и тестирования на сервере:
#          sudo apt-get update
#          sudo apt-get install -y mysql-server
#          sudo systemctl start mysql
#
#      - name: Run tests
#        run: mvn test
